<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:include filename="$(find kenny_description)/urdf/base/base.transmissions.xacro"/>

  <!--  ++++++++++++++++++++++++++++++++++++++++ -->

  <xacro:property name="base_length" value="1.176" />
  <xacro:property name="base_width" value="0.444" />
  <xacro:property name="base_depth" value="0.308" />


  <xacro:property name="wheel_length" value="1.135" />
  <xacro:property name="wheel_width" value="0.12" />
  <xacro:property name="wheel_rad" value="0.2" />
  <xacro:property name="wheel_sep" value="0.6" />

  <xacro:property name="caster_rad" value="${wheel_rad - (base_depth/2)}"/>

  <!-- <xacro:property name="off_floor" value="${wheel_rad - base_depth/2}" /> -->
  <xacro:property name="off_floor" value="${wheel_rad}" />


  <!--  ++++++++++++++++++++++++++++++++++++++++ -->


  <!-- <xacro:macro name="wheel" params="name sidereflect frontback"> -->
  <xacro:macro name="wheel" params="name reflect">
    <link name="${name}">
      
      <visual>
        <geometry>
          <!-- <box size="${wheel_length} ${wheel_width} ${wheel_depth}"/> -->
            <cylinder length="${wheel_width}" radius="${wheel_rad}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="black"/>
      </visual>

      <collision>
        <geometry>
            <!-- <box size="${wheel_length} ${wheel_width} ${wheel_depth}"/> -->
            <cylinder length="${wheel_width}" radius="${wheel_rad}"/>
        </geometry>
        <!-- <origin xyz="0 0 0"/> -->
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2"/>
        <inertia ixx="0.02467" ixy="0.0" ixz="0.0" iyy="0.04411" iyz="0.0" izz="0.02467"/>
      </inertial>
    </link>
    
    <joint name="joint_base_${name}" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <!-- <origin xyz="${frontback * wheel_sep/2} ${sidereflect * 0.5*(base_width+wheel_width)} ${off_floor}" rpy="1.57 0 0"/> -->
      <!-- <origin xyz="0 ${reflect * 0.5*(base_width+wheel_width)} ${off_floor}" rpy="1.57 0 0"/> -->
      <origin xyz="0 ${reflect * 0.5*(base_width+wheel_width)} 0" rpy="1.57 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="caster" params="name reflect">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <sphere radius="${caster_rad}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_rad}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.02467" ixy="0.0" ixz="0.0" iyy="0.04411" iyz="0.0" izz="0.02467"/>
      </inertial>
    </link>
    <joint name="joint_base_${name}" type="revolute">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${reflect*(base_length/2-caster_rad)} 0 ${-base_depth/2}"/>
      <axis xyz="0 0 1"/>
      <limit effort="1000" lower="0" upper="0" velocity="0"/>
    </joint>
  </xacro:macro>


  <!--  ++++++++++++++++++++++++++++++++++++++++ -->

  <xacro:macro name="kenny_base" >
  <!-- footprint link is used for calculating distances between 
        the robot and obstacles -->
    <link name="base_footprint">
      <origin xyz="0 0 0"/>
    </link>

    <link name="base_link">
      <visual>
        <geometry>
            <box size="${base_length} ${base_width} ${base_depth}"/>
        </geometry>
        <origin xyz="0 0 0"/>
        <material name="yellow"/>
      </visual>
      <collision>
        <geometry>
            <box size="${base_length} ${base_width} ${base_depth}"/>
        </geometry>
        <origin xyz="0 0 0" />
      </collision>
    </link>
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${off_floor}" />
    </joint>

    <link name="inertial_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="200"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 ${off_floor+0.5*base_depth}" rpy="0 0 0"/>
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>
    
    <!-- <link name="dummy"></link>
    <joint name="dummy_joint" type="fixed">
      <parent link="dummy"/>
      <child link="inertial_link"/>
    </joint> -->

    <!-- 4 Wheel Kenny -->
    <xacro:wheel name="wheel_right" reflect="1" />
    <xacro:wheel name="wheel_left" reflect="-1"/>
    <xacro:kenny_wheel_joint_transmission name="base_wheel_right"/>
    <xacro:kenny_wheel_joint_transmission name="base_wheel_left"/>

    <!-- 4 Wheel Kenny -->
    <!-- <xacro:wheel name="wheel_rfront" sidereflect="1" frontback="1"/>
    <xacro:wheel name="wheel_rback" sidereflect="1" frontback="-1"/>
    <xacro:wheel name="wheel_lfront" sidereflect="-1" frontback="1"/>
    <xacro:wheel name="wheel_lback" sidereflect="-1" frontback="-1"/>
     -->
    <!-- Transmission Macros for wheels -->
    <!-- <xacro:kenny_wheel_joint_transmission name="base_wheel_rfront"/>
    <xacro:kenny_wheel_joint_transmission name="base_wheel_rback"/>
    <xacro:kenny_wheel_joint_transmission name="base_wheel_lfront"/>
    <xacro:kenny_wheel_joint_transmission name="base_wheel_lback"/> -->

    <xacro:caster name="caster_front" reflect="1"/>
    <xacro:caster name="caster_back" reflect="-1"/>

    <!-- Gazebo Macro -->
  </xacro:macro>

</robot>