<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- <xacro:include filename="$(find kenny_description)/urdf/base/base.transmission.xacro"/> -->
  <xacro:include filename="$(find kenny_description)/urdf/base/base.gazebo.urdf"/>
  <xacro:include filename="$(find kenny_description)/urdf/base/base.transmissions.xacro"/>

  <!--  ++++++++++++++++++++++++++++++++++++++++ -->

  <xacro:property name="base_length" value="1.176" />
  <xacro:property name="base_width" value="0.444" />
  <xacro:property name="base_depth" value="0.308" />


  <xacro:property name="wheel_length" value="1.135" />
  <xacro:property name="wheel_width" value="0.12" />
  <xacro:property name="wheel_rad" value="0.2" />
  <xacro:property name="wheel_sep" value="0.6" />

  <xacro:property name="off_floor" value="${wheel_rad - base_depth/2}" />


  <!--  ++++++++++++++++++++++++++++++++++++++++ -->


  <xacro:macro name="wheel" params="name sidereflect frontback">
    <link name="${name}">
      
      <visual>
        <geometry>
          <!-- <box size="${wheel_length} ${wheel_width} ${wheel_depth}"/> -->
            <cylinder length="${wheel_width}" radius="${wheel_rad}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <material name="black"/>
      </visual>

      <collision>
        <geometry>
            <!-- <box size="${wheel_length} ${wheel_width} ${wheel_depth}"/> -->
            <cylinder length="${wheel_width}" radius="${wheel_rad}"/>
        </geometry>
        <!-- <origin xyz="0 0 0"/> -->
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
    </link>
    
    <joint name="joint_base_${name}" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${frontback * wheel_sep/2} ${sidereflect * 0.5*(base_width+wheel_width)} ${off_floor}" />
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>


  <!--  ++++++++++++++++++++++++++++++++++++++++ -->

  <xacro:macro name="kenny_base" >
    <link name="base_footprint"/>

    <link name="base_link">
      <visual>
        <geometry>
            <box size="${base_length} ${base_width} ${base_depth}"/>
        </geometry>
        <origin xyz="0 0 ${off_floor+base_depth/2}" />
        <material name="yellow"/>
      </visual>
      <collision>
        <geometry>
            <box size="${base_length} ${base_width} ${base_depth}"/>
        </geometry>
        <!-- <origin xyz="0 0 ${off_floor+base_depth/2}" /> -->
        <origin xyz="0 0 0" />
      </collision>
    </link>
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
    </joint>

    <link name="inertial_link">
      <inertial>
        <origin xyz="0 0 ${off_floor+0.5*base_depth}" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>
    
    <!-- <link name="dummy"></link>
    <joint name="dummy_joint" type="fixed">
      <parent link="dummy"/>
      <child link="inertial_link"/>
    </joint> -->

    <xacro:wheel name="wheel_rfront" sidereflect="1" frontback="1"/>
    <xacro:wheel name="wheel_rback" sidereflect="1" frontback="-1"/>
    <xacro:wheel name="wheel_lfront" sidereflect="-1" frontback="1"/>
    <xacro:wheel name="wheel_lback" sidereflect="-1" frontback="-1"/>
    
    <!-- Transmission Macros for wheels -->
    <xacro:kenny_wheel_joint_transmission name="base_wheel_rfront"/>
    <xacro:kenny_wheel_joint_transmission name="base_wheel_rback"/>
    <xacro:kenny_wheel_joint_transmission name="base_wheel_lfront"/>
    <xacro:kenny_wheel_joint_transmission name="base_wheel_lback"/>


    <!-- Gazebo Macro -->
    <xacro:base_gazebo/>
  </xacro:macro>

</robot>