kenny:
  hardware_interface:
     loop_hz: 10 # hz
     joints:
       - joint_base_wheel_left
       - joint_base_wheel_right
       - J0
       - J1
       - J2
       - J3
       - joint_camera_z_rotation
       - joint_camera_y_rotation