<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kenny_arm">
<!-- <robot xmlns:xacro="http://www.ros.org/wiki/xacro"> -->

  <xacro:include filename="$(find kenny_description)/urdf/arm/arm.transmission.xacro"/>
  <xacro:include filename="$(find kenny_description)/urdf/arm/arm.gazebo.urdf"/>

  <!--  ++++++++++++++++++++++++++++++++++++++++ -->

  <xacro:property name="arm_length" value="0.73"/>
  <xacro:property name="arm_width" value="0.378"/>
  <xacro:property name="arm_depth" value="0.232"/>

  <xacro:property name="forearm_length" value="0.64"/>
  <xacro:property name="forearm_width" value="0.389"/>
  <xacro:property name="forearm_depth" value="0.18"/>
  <xacro:property name="forearm_default_rotation" value="-0.65"/>

  <xacro:property name="hand_length" value="0.788"/>
  <xacro:property name="hand_width" value="0.06"/>
  <xacro:property name="hand_depth" value="0.08"/>

  <xacro:property name="reel_rad" value="0.199" />
  <xacro:property name="reel_length" value="0.09" />
  <xacro:property name="reel_base_offset" value="0.0" />

  <!--  ++++++++++++++++++++++++++++++++++++++++ -->

  <!-- <xacro:macro name="kenny_arm" params="parent"> params="parent *origin"> -->
  <xacro:macro name="kenny_arm" params="parent *origin">

    <link name="dummy_reel">
      <!-- <visual>
        <geometry>
          <cylinder length="${reel_length/4}" radius="${reel_rad}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="yellow"/>
      </visual> -->

      <!-- <collision>
        <geometry>
            <cylinder length="${reel_length}" radius="${reel_rad}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0"/>
      </inertial> -->
    </link>
    <joint name="dummy_reel_joint" type="revolute">
      <!-- <parent link="base_link"/> -->
      <parent link="${parent}"/>
      <child link="dummy_reel"/>
      <xacro:insert_block name="origin"/>
      <axis xyz="0 0 1"/>
      <limit effort="1000.0" lower="0" upper="0" velocity="0"/>
    </joint>



    <link name="reel">
      <visual>
        <geometry>
          <cylinder length="${reel_length}" radius="${reel_rad}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="yellow"/>
      </visual>

      <collision>
        <geometry>
            <cylinder length="${reel_length}" radius="${reel_rad}"/>
        </geometry>
        <!-- <origin xyz="0 0 0"/> -->
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
    <!-- joint between reel and base - allows for motorised reel -->
    <joint name="reel_joint" type="revolute">
      <parent link="dummy_reel"/>
      <child link="reel"/>
      <axis xyz="0 0 1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- <xacro:insert_block name="origin" /> -->
      <limit effort="1000.0" lower="-180" upper="180" velocity="2"/>
    </joint>



    <link name="arm">
      <visual>
        <geometry>
          <box size="${arm_length} ${arm_width} ${arm_depth}"/>
        </geometry>
        <material name="yellow"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>

      <collision>
        <geometry>
          <box size="${arm_length} ${arm_width} ${arm_depth}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>

    <!-- link between reel and arm -->
    <joint name="shoulder" type="revolute">
        <parent link="dummy_reel"/>
        <child link="arm"/>
        <origin xyz="${-1*reel_base_offset} 0 ${reel_length/2+arm_depth/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="-20" upper="20" velocity="0"/>
    </joint>



    <link name="forearm">
      <visual>
        <geometry>
            <box size="${forearm_depth} ${forearm_width} ${forearm_length}"/>
        </geometry>
        <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
        <material name="yellow"/>
      </visual>

      <collision>
        <geometry>
            <box size="${forearm_depth} ${forearm_width} ${forearm_length}"/>
        </geometry>
        <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>

    <!-- joint between arm and forearm -->
    <joint name="elbow" type="revolute">
      <parent link="arm"/>
      <child link="forearm"/>
      <axis xyz="0 1 0"/>
      <origin xyz="${arm_length/2} 0 0" rpy="0 ${forearm_default_rotation} 0"/>
      <!-- <origin xyz="${arm_length/2-forearm_depth/2} 0 0" rpy="0 0 0"/> -->
      <limit effort="1000.0" lower="0" upper="1.65" velocity="0.5"/>
    </joint>



    <link name="hand">
      <visual>
        <geometry>
          <box size="${hand_length} ${hand_width} ${hand_depth}"/>
        </geometry>
        <origin xyz="${hand_length/2} 0 0" rpy="0 0 0"/>
        <material name="yellow"/>
      </visual>

      <collision>
        <geometry>
          <box size="${hand_length} ${hand_width} ${hand_depth}"/>
        </geometry>
        <origin xyz="${hand_length/2} 0 0" rpy="0 0 0"/>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
  <!-- joint between forearm and hand -->
    <joint name="wrist" type="revolute">
      <parent link="forearm"/>
      <child link="hand"/>
      <axis xyz="0 1 0"/>
      <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
      <limit effort="1000.0" lower="0" upper="0.84" velocity="0.5"/>
    </joint>



    <!-- Transmission Macros -->
    <xacro:kenny_arm_joint_transmission name="shoulder"/>
    <xacro:kenny_arm_joint_transmission name="elbow"/>
    <xacro:kenny_arm_joint_transmission name="wrist"/>

    <xacro:kenny_arm_joint_transmission name="reel_joint"/>

    <!-- Gazebo Macro -->
    <xacro:kenny_arm_gazebo/>

  </xacro:macro>

</robot>