<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kenny_arm">
<!-- <robot xmlns:xacro="http://www.ros.org/wiki/xacro"> -->

  <xacro:include filename="$(find kenny_description)/urdf/arm/arm.transmission.xacro"/>
  <xacro:include filename="$(find kenny_description)/urdf/arm/arm.gazebo.urdf"/>

  <!--  ++++++++++++++++++++++++++++++++++++++++ -->

  <xacro:property name="link1_length" value="0.73"/>
  <xacro:property name="link1_width" value="0.378"/>
  <xacro:property name="link1_depth" value="0.232"/>

  <xacro:property name="link2_length" value="0.64"/>
  <xacro:property name="link2_width" value="0.389"/>
  <xacro:property name="link2_depth" value="0.18"/>
  <xacro:property name="link2_default_rotation" value="-0.65"/>

  <xacro:property name="link3_length" value="0.788"/>
  <xacro:property name="link3_width" value="0.06"/>
  <xacro:property name="link3_depth" value="0.08"/>

  <xacro:property name="reel_rad" value="0.199" />
  <xacro:property name="reel_length" value="0.09" />
  <xacro:property name="reel_base_offset" value="0.0" />

  <!--  ++++++++++++++++++++++++++++++++++++++++ -->

  <xacro:macro name="kenny_arm" params="parent"> <!-- params="parent *origin"> -->

    <link name="dummy_reel">
      <visual>
        <geometry>
          <cylinder length="${reel_length/4}" radius="${reel_rad}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="yellow"/>
      </visual>

      <collision>
        <geometry>
            <cylinder length="${reel_length}" radius="${reel_rad}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0"/>
      </inertial>
    </link>
    <joint name="dummy_J3" type="revolute">
      <parent link="${parent}"/>
      <child link="dummy_reel"/>
      <axis xyz="0 0 0"/>
      <limit effort="1000.0" lower="0" upper="0" velocity="0"/>

    </joint>



    <link name="reel">
      <visual>
        <geometry>
          <cylinder length="${reel_length}" radius="${reel_rad}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="yellow"/>
      </visual>

      <collision>
        <geometry>
            <cylinder length="${reel_length}" radius="${reel_rad}"/>
        </geometry>
        <!-- <origin xyz="0 0 0"/> -->
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
    <!-- joint between reel and base - allows for motorised reel -->
    <joint name="J3" type="revolute">
      <parent link="dummy_reel"/>
      <child link="reel"/>
      <axis xyz="0 0 1"/>
      <!-- <xacro:insert_block name="origin" /> -->
      <limit effort="1000.0" lower="0" upper="0" velocity="0"/>
    </joint>



    <link name="arm_link1">
      <visual>
        <geometry>
          <box size="${link1_length} ${link1_width} ${link1_depth}"/>
        </geometry>
        <material name="yellow"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>

      <collision>
        <geometry>
          <box size="${link1_length} ${link1_width} ${link1_depth}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>

    <!-- link between reel and link1 -->
    <joint name="J0" type="revolute">
        <parent link="dummy_reel"/>
        <child link="arm_link1"/>
        <origin xyz="${-1*reel_base_offset} 0 ${reel_length/2+link1_depth/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="-20" upper="20" velocity="0"/>
    </joint>



    <link name="arm_link2">
      <visual>
        <geometry>
            <box size="${link2_depth} ${link2_width} ${link2_length}"/>
        </geometry>
        <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
        <material name="yellow"/>
      </visual>

      <collision>
        <geometry>
            <box size="${link2_depth} ${link2_width} ${link2_length}"/>
        </geometry>
        <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>

    <!-- joint between link1 and link2 -->
    <joint name="J1" type="revolute">
      <parent link="arm_link1"/>
      <child link="arm_link2"/>
      <axis xyz="0 1 0"/>
      <origin xyz="${link1_length/2} 0 0" rpy="0 ${link2_default_rotation} 0"/>
      <!-- <origin xyz="${link1_length/2-link2_depth/2} 0 0" rpy="0 0 0"/> -->
      <limit effort="1000.0" lower="0" upper="1.65" velocity="0.5"/>
    </joint>



    <link name="arm_link3">
      <visual>
        <geometry>
          <box size="${link3_length} ${link3_width} ${link3_depth}"/>
        </geometry>
        <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
        <material name="yellow"/>
      </visual>

      <collision>
        <geometry>
          <box size="${link3_length} ${link3_width} ${link3_depth}"/>
        </geometry>
        <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.2" ixy="0.0" ixz="0.0" iyy="0.2" iyz="0.0" izz="0.2"/>
      </inertial>
    </link>
  <!-- joint between link 2 and link 3 -->
    <joint name="J2" type="revolute">
      <parent link="arm_link2"/>
      <child link="arm_link3"/>
      <axis xyz="0 1 0"/>
      <origin xyz="0 0 ${link2_length}" rpy="0 0 0"/>
      <limit effort="1000.0" lower="0" upper="0.84" velocity="0.5"/>
    </joint>



    <!-- Transmission Macros -->
    <xacro:kenny_arm_joint_transmission name="J0"/>
    <xacro:kenny_arm_joint_transmission name="J1"/>
    <xacro:kenny_arm_joint_transmission name="J2"/>

    <xacro:kenny_arm_joint_transmission name="J3"/>

    <!-- Gazebo Macro -->
    <xacro:kenny_arm_gazebo/>

  </xacro:macro>

</robot>