controller_list:
  - name: fake_arm_controller
    joints:
      - joint_reel_link1
      - joint_link1_link2
      - joint_link2_link3
initial:  # Define initial robot poses.
  - group: arm
    pose: ready