controller_list:
  - name: fake_arm_controller
    joints:
      - joint_reel_arm
      - joint_arm_forearm
      - joint_forearm_hand
initial:  # Define initial robot poses.
  - group: arm
    pose: ready