# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: ready
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_reel_link1
    - joint_camera_z_rotation
    - joint_camera_y_rotation
    - joint_link1_link2
    - joint_link2_link3
    - joint_base_wheel_left
    - joint_base_wheel_right
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_reel_link1
    - joint_link1_link2
    - joint_link2_link3
  gains:
    joint_reel_link1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_link1_link2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_link2_link3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1